[workspace]
members = [
	"tools/ridl",
	"rtl",
	"kernel",
	"userspace/services/roottask",
	"userspace/apps/console",
	"xtask",
	"userspace/services/uart",
	"loader", "loader_protocol", "hal", "userspace/services/pci",
]

resolver = "2"
