[workspace]
members = [
	"tools/ridl",
	"rtl",
	"kernel",
	"userspace/services/roottask",
	"userspace/apps/client",
	"xtask",
	"userspace/services/uart",
	"loader", "loader_protocol",
]

resolver = "2"
